// Kavram aramasında seçilebilecek medeniyetler, ülkeler ve ünlü kişiler.
// Ülkeler ISO 3166 koduyla tutulur; görünen ad Intl.DisplayNames ile
// seçili arayüz diline göre üretilir. Medeniyet ve kişiler iki dillidir.

export const CIVILIZATIONS = {
  label: { tr: 'Kadim Medeniyetler', en: 'Ancient Civilizations' },
  options: [
    { tr: 'İnka Medeniyeti', en: 'Inca Civilization' },
    { tr: 'Maya Medeniyeti', en: 'Maya Civilization' },
    { tr: 'Aztek Medeniyeti', en: 'Aztec Civilization' },
    { tr: 'Antik Mısır', en: 'Ancient Egypt' },
    { tr: 'Mezopotamya (Sümer, Babil, Akad)', en: 'Mesopotamia (Sumer, Babylon, Akkad)' },
    { tr: 'Antik Yunan', en: 'Ancient Greece' },
    { tr: 'Roma İmparatorluğu', en: 'Roman Empire' },
    { tr: 'Bizans', en: 'Byzantium' },
    { tr: 'Antik Pers', en: 'Ancient Persia' },
    { tr: 'Fenike', en: 'Phoenicia' },
    { tr: 'Hitit', en: 'Hittite Empire' },
    { tr: 'Kartaca', en: 'Carthage' },
    { tr: 'Kelt Medeniyeti', en: 'Celtic Civilization' },
    { tr: 'Vikingler / İskandinav Mitolojisi', en: 'Vikings / Norse Mythology' },
    { tr: 'Göktürkler / Eski Türkler', en: 'Göktürks / Old Turkic Peoples' },
    { tr: 'Osmanlı İmparatorluğu', en: 'Ottoman Empire' },
    { tr: 'Endülüs', en: 'Al-Andalus' },
    { tr: 'Moğol İmparatorluğu', en: 'Mongol Empire' },
    { tr: 'Antik Çin', en: 'Ancient China' },
    { tr: 'Antik Hindistan (Vedik / Sanskrit)', en: 'Ancient India (Vedic / Sanskrit)' },
    { tr: 'Aksum (Antik Habeşistan)', en: 'Axum (Ancient Abyssinia)' },
    { tr: 'Kuzey Amerika Yerlileri', en: 'Native North Americans' },
    { tr: 'Aborjin Avustralya', en: 'Aboriginal Australia' },
    { tr: 'Maori Kültürü', en: 'Māori Culture' },
    { tr: 'Polinezya', en: 'Polynesia' },
  ],
};

export const COUNTRY_GROUPS = [
  {
    label: { tr: 'Avrupa', en: 'Europe' },
    codes: [
      'DE', 'AD', 'AL', 'AT', 'BE', 'BY', 'GB', 'BA', 'BG', 'CZ', 'DK', 'EE',
      'FI', 'FR', 'HR', 'NL', 'IE', 'ES', 'SE', 'CH', 'IT', 'IS', 'ME', 'XK',
      'MK', 'LV', 'LI', 'LT', 'LU', 'HU', 'MT', 'MD', 'MC', 'NO', 'PL', 'PT',
      'RO', 'RU', 'SM', 'RS', 'SK', 'SI', 'UA', 'VA', 'GR',
    ],
  },
  {
    label: { tr: 'Asya', en: 'Asia' },
    codes: [
      'AF', 'AZ', 'BD', 'BT', 'BN', 'CN', 'TL', 'ID', 'AM', 'PH', 'KR', 'GE',
      'IN', 'JP', 'KH', 'KZ', 'KG', 'KP', 'LA', 'MY', 'MV', 'MN', 'MM', 'NP',
      'UZ', 'PK', 'SG', 'LK', 'TJ', 'TH', 'TW', 'TM', 'VN',
    ],
  },
  {
    label: { tr: 'Orta Doğu', en: 'Middle East' },
    codes: [
      'BH', 'AE', 'PS', 'IQ', 'IR', 'IL', 'QA', 'CY', 'KW', 'LB', 'SY', 'SA',
      'TR', 'OM', 'JO', 'YE',
    ],
  },
  {
    label: { tr: 'Afrika', en: 'Africa' },
    codes: [
      'AO', 'BJ', 'BW', 'BF', 'BI', 'DZ', 'DJ', 'TD', 'CD', 'GQ', 'ER', 'SZ',
      'ET', 'MA', 'CI', 'GA', 'GM', 'GH', 'GN', 'GW', 'ZA', 'SS', 'CM', 'KE',
      'KM', 'CG', 'LS', 'LR', 'LY', 'MG', 'MW', 'ML', 'MU', 'EG', 'MR', 'MZ',
      'NA', 'NE', 'NG', 'CF', 'RW', 'ST', 'SN', 'SC', 'SL', 'SO', 'SD', 'TZ',
      'TG', 'TN', 'UG', 'CV', 'ZM', 'ZW',
    ],
  },
  {
    label: { tr: 'Kuzey Amerika & Karayipler', en: 'North America & Caribbean' },
    codes: [
      'US', 'AG', 'BS', 'BB', 'BZ', 'DM', 'DO', 'SV', 'GD', 'GT', 'HT', 'HN',
      'JM', 'CA', 'CR', 'CU', 'MX', 'NI', 'PA', 'KN', 'LC', 'VC', 'TT',
    ],
  },
  {
    label: { tr: 'Güney Amerika', en: 'South America' },
    codes: ['AR', 'BO', 'BR', 'EC', 'GY', 'CO', 'PY', 'PE', 'SR', 'CL', 'UY', 'VE'],
  },
  {
    label: { tr: 'Okyanusya', en: 'Oceania' },
    codes: [
      'AU', 'FJ', 'KI', 'MH', 'FM', 'NR', 'PW', 'PG', 'WS', 'SB', 'TO', 'TV',
      'VU', 'NZ',
    ],
  },
];

export const PERSON_GROUPS = [
  {
    label: { tr: 'Türk Büyükleri', en: 'Turkish Greats' },
    options: [
      { tr: 'Mustafa Kemal Atatürk', en: 'Mustafa Kemal Atatürk' },
      { tr: 'Mevlânâ Celâleddîn-i Rûmî', en: 'Rumi (Mevlânâ)' },
      { tr: 'Yunus Emre', en: 'Yunus Emre' },
      { tr: 'Hacı Bektaş-ı Veli', en: 'Haji Bektash Veli' },
      { tr: 'Ömer Hayyam', en: 'Omar Khayyam' },
      { tr: 'Ali Kuşçu', en: 'Ali Qushji' },
      { tr: 'Fatih Sultan Mehmet', en: 'Mehmed the Conqueror' },
      { tr: 'Kanuni Sultan Süleyman', en: 'Suleiman the Magnificent' },
      { tr: 'Nâzım Hikmet', en: 'Nâzım Hikmet' },
      { tr: 'Sabahattin Ali', en: 'Sabahattin Ali' },
      { tr: 'Ahmet Hamdi Tanpınar', en: 'Ahmet Hamdi Tanpınar' },
      { tr: 'Aşık Veysel', en: 'Aşık Veysel' },
    ],
  },
  {
    label: { tr: 'Antik Filozoflar', en: 'Ancient Philosophers' },
    options: [
      { tr: 'Sokrates', en: 'Socrates' },
      { tr: 'Platon', en: 'Plato' },
      { tr: 'Aristoteles', en: 'Aristotle' },
      { tr: 'Çiçero', en: 'Cicero' },
      { tr: 'Seneca', en: 'Seneca' },
      { tr: 'Marcus Aurelius', en: 'Marcus Aurelius' },
      { tr: 'Epiktetos', en: 'Epictetus' },
      { tr: 'Epikür', en: 'Epicurus' },
      { tr: 'Herakleitos', en: 'Heraclitus' },
      { tr: 'Diyojen', en: 'Diogenes' },
      { tr: 'Konfüçyüs', en: 'Confucius' },
      { tr: 'Lao Tzu', en: 'Laozi' },
      { tr: 'Buda', en: 'Buddha' },
      { tr: 'Sun Tzu', en: 'Sun Tzu' },
    ],
  },
  {
    label: { tr: 'Düşünürler & Filozoflar', en: 'Thinkers & Philosophers' },
    options: [
      { tr: 'Friedrich Nietzsche', en: 'Friedrich Nietzsche' },
      { tr: 'Immanuel Kant', en: 'Immanuel Kant' },
      { tr: 'Arthur Schopenhauer', en: 'Arthur Schopenhauer' },
      { tr: 'Søren Kierkegaard', en: 'Søren Kierkegaard' },
      { tr: 'Jean-Paul Sartre', en: 'Jean-Paul Sartre' },
      { tr: 'Albert Camus', en: 'Albert Camus' },
      { tr: 'Simone de Beauvoir', en: 'Simone de Beauvoir' },
      { tr: 'Hannah Arendt', en: 'Hannah Arendt' },
      { tr: 'Michel de Montaigne', en: 'Michel de Montaigne' },
      { tr: 'Baruch Spinoza', en: 'Baruch Spinoza' },
      { tr: 'John Stuart Mill', en: 'John Stuart Mill' },
      { tr: 'İbn-i Haldun', en: 'Ibn Khaldun' },
      { tr: 'Erasmus', en: 'Erasmus' },
    ],
  },
  {
    label: { tr: 'Yazarlar & Şairler', en: 'Writers & Poets' },
    options: [
      { tr: 'William Shakespeare', en: 'William Shakespeare' },
      { tr: 'Johann Wolfgang von Goethe', en: 'Johann Wolfgang von Goethe' },
      { tr: 'Lev Tolstoy', en: 'Leo Tolstoy' },
      { tr: 'Fyodor Dostoyevski', en: 'Fyodor Dostoevsky' },
      { tr: 'Franz Kafka', en: 'Franz Kafka' },
      { tr: 'Oscar Wilde', en: 'Oscar Wilde' },
      { tr: 'Mark Twain', en: 'Mark Twain' },
      { tr: 'Victor Hugo', en: 'Victor Hugo' },
      { tr: 'Hâfız-ı Şirâzî', en: 'Hafez' },
      { tr: 'Halil Cibran', en: 'Kahlil Gibran' },
      { tr: 'Rabindranath Tagore', en: 'Rabindranath Tagore' },
      { tr: 'Pablo Neruda', en: 'Pablo Neruda' },
      { tr: 'Emily Dickinson', en: 'Emily Dickinson' },
      { tr: 'Virginia Woolf', en: 'Virginia Woolf' },
      { tr: 'Jorge Luis Borges', en: 'Jorge Luis Borges' },
      { tr: 'Antoine de Saint-Exupéry', en: 'Antoine de Saint-Exupéry' },
      { tr: 'Samuel Beckett', en: 'Samuel Beckett' },
    ],
  },
  {
    label: { tr: 'Liderler & Devlet İnsanları', en: 'Leaders & Statespeople' },
    options: [
      { tr: 'Winston Churchill', en: 'Winston Churchill' },
      { tr: 'Abraham Lincoln', en: 'Abraham Lincoln' },
      { tr: 'Mahatma Gandhi', en: 'Mahatma Gandhi' },
      { tr: 'Nelson Mandela', en: 'Nelson Mandela' },
      { tr: 'Kraliçe I. Elizabeth', en: 'Queen Elizabeth I' },
      { tr: 'Kraliçe II. Elizabeth', en: 'Queen Elizabeth II' },
      { tr: 'Napolyon Bonapart', en: 'Napoleon Bonaparte' },
      { tr: 'Julius Caesar', en: 'Julius Caesar' },
      { tr: 'Martin Luther King', en: 'Martin Luther King Jr.' },
      { tr: 'John F. Kennedy', en: 'John F. Kennedy' },
      { tr: 'Eleanor Roosevelt', en: 'Eleanor Roosevelt' },
      { tr: 'Selahaddin Eyyubi', en: 'Saladin' },
    ],
  },
  {
    label: { tr: 'Bilim İnsanları', en: 'Scientists' },
    options: [
      { tr: 'Albert Einstein', en: 'Albert Einstein' },
      { tr: 'Isaac Newton', en: 'Isaac Newton' },
      { tr: 'Marie Curie', en: 'Marie Curie' },
      { tr: 'Nikola Tesla', en: 'Nikola Tesla' },
      { tr: 'Charles Darwin', en: 'Charles Darwin' },
      { tr: 'Galileo Galilei', en: 'Galileo Galilei' },
      { tr: 'İbn-i Sina', en: 'Avicenna (Ibn Sina)' },
      { tr: 'Stephen Hawking', en: 'Stephen Hawking' },
      { tr: 'Carl Sagan', en: 'Carl Sagan' },
      { tr: 'Richard Feynman', en: 'Richard Feynman' },
    ],
  },
  {
    label: { tr: 'Sanatçılar', en: 'Artists' },
    options: [
      { tr: 'Leonardo da Vinci', en: 'Leonardo da Vinci' },
      { tr: 'Michelangelo', en: 'Michelangelo' },
      { tr: 'Vincent van Gogh', en: 'Vincent van Gogh' },
      { tr: 'Pablo Picasso', en: 'Pablo Picasso' },
      { tr: 'Frida Kahlo', en: 'Frida Kahlo' },
      { tr: 'Ludwig van Beethoven', en: 'Ludwig van Beethoven' },
      { tr: 'Wolfgang Amadeus Mozart', en: 'Wolfgang Amadeus Mozart' },
      { tr: 'Charlie Chaplin', en: 'Charlie Chaplin' },
    ],
  },
];
